deploy-development:
  script:
  - ssh webber@api01 -C "cd ~/dev-cd/   && git fetch --tags && git checkout -f origin/development && ./buildate && echo $CI_BUILD_REF_NAME > public/version"
  type: deploy
  tags:
  only:
  - development
deploy-testing:
  script:
  - ssh webber@api01 -C "cd ~/stage-cd/ && git fetch --tags && git checkout -f origin/testing     && ./buildate && echo $CI_BUILD_REF_NAME > public/version"
  type: deploy
  tags:
  only:
  - testing
deploy-production:
  script:
  - ssh webber@api01 -C "cd ~/cd/       && git fetch --tags && git checkout -f $CI_BUILD_REF_NAME && ./buildate && echo $CI_BUILD_REF_NAME > public/version"
  type: deploy
  tags:
  only:
  - /^v([0-9]+).([0-9]+).([0-9]+)$/
