session_name: neo#cebumodeling#com
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: vim
  panes:
    - vim -c NERDTree
  focus: true
- window_name: git
  panes:
    - shell_command:
      - git fetch
      - git status
- window_name: server
  panes:
    - shell_command:
      - ./update
      - ./server
