version: '3.6'
services:
  app:
    build : docker
    volumes:
      - .:/app
      - /home/webber/.ssh:/root/.ssh
    expose:
      - 80
    networks:
      - frontend

networks:
  frontend:
    external:
      name: frontend
