#!/bin/bash
./composer install --optimize-autoloader --no-ansi --no-progress --no-dev && ./artisan route:cache && ./artisan config:cache && rm node_modules/jscore -rf && npm install && bower install --allow-root
